-- https://github.com/rcarriga/nvim-dap-ui
return function(C)
  return {
    DapUINormal = { link = "Normal" },
    DapUIVariable = { link = "Normal" },
    DapUIScope = { fg = C.lightCyan },
    DapUIType = { fg = C.violet },
    DapUIValue = { link = "Normal" },
    DapUIModifiedValue = { fg = C.lightCyan, bold = true },
    DapUIDecoration = { fg = C.lightCyan },
    DapUIThread = { fg = C.lightYellow },
    DapUIStoppedThread = { fg = C.lightCyan },
    DapUIFrameName = { link = "Normal" },
    DapUISource = { fg = C.violet },
    DapUILineNumber = { fg = C.lightCyan },
    DapUIFloatNormal = { link = "NormalFloat" },
    DapUIFloatBorder = { fg = C.lightCyan },
    DapUIWatchesEmpty = { fg = C.lightRed },
    DapUIWatchesValue = { fg = C.lightYellow },
    DapUIWatchesError = { fg = C.lightRed },
    DapUIBreakpointsPath = { fg = C.lightCyan },
    DapUIBreakpointsInfo = { fg = C.lightYellow },
    DapUIBreakpointsCurrentLine = { fg = C.lightYellow, bold = true },
    DapUIBreakpointsLine = { link = "DapUILineNumber" },
    DapUIBreakpointsDisabledLine = { fg = C.grey1 },
    DapUICurrentFrameName = { link = "DapUIBreakpointsCurrentLine" },
    DapUIStepOver = { fg = C.lightCyan },
    DapUIStepInto = { fg = C.lightCyan },
    DapUIStepBack = { fg = C.lightCyan },
    DapUIStepOut = { fg = C.lightCyan },
    DapUIStop = { fg = C.lightRed },
    DapUIPlayPause = { fg = C.lightYellow },
    DapUIRestart = { fg = C.lightYellow },
    DapUIUnavailable = { fg = C.grey1 },
    DapUIWinSelect = { fg = C.lightCyan, bold = true },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
  }
end
