-- Always-on highlights: editor UI, legacy syntax, diagnostics, LSP, treesitter.
---@param C table<string, string>
---@param opts { transparent: boolean }
---@return table<string, vim.api.keyset.highlight>
return function(C, opts)
  return {
    -- ┌──────────────────────────┐
    -- │ Builtin highlight groups │
    -- └──────────────────────────┘
    ColorColumn = { bg = C.bg1 },
    Conceal = { fg = C.grey1, bold = true },
    Cursor = { reverse = true },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorColumn = { link = "CursorLine" },
    CursorLine = { bg = C.bg2 },
    Directory = { fg = C.green },
    DiffAdd = { bg = C.sub_green0 },
    DiffChange = { bg = C.sub_blue0 },
    DiffDelete = { bg = C.sub_red0 },
    DiffText = { fg = C.bg0, bg = C.fg0 },
    -- opaque: hide "~" by matching bg; transparent: bg is unknown, so keep it barely visible
    EndOfBuffer = { fg = opts.transparent and C.bg3 or C.bg0 },
    TermCursor = { link = "Cursor" },
    TermCursorNC = { link = "Cursor" },
    ErrorMsg = { fg = C.darkRed, bold = true, underline = true },
    WinSeparator = { fg = C.bg2, bg = "NONE" },
    Folded = { fg = C.grey1 },
    FoldColumn = { fg = C.grey1 },
    SignColumn = { fg = C.fg0 },
    IncSearch = { fg = C.bg0, bg = C.lightGreen },
    Substitute = { fg = C.bg0, bg = C.yellow },
    LineNr = { fg = C.grey0 },
    CursorLineNr = { fg = C.fg0, bold = true },
    MatchParen = { bg = C.bg2, bold = true },
    ModeMsg = { fg = C.fg0, bold = true },
    MsgArea = { link = "StatusLine" },
    MsgSeparator = { bg = C.bg2 },
    MoreMsg = { fg = C.yellow, bold = true },
    NonText = { fg = C.grey0 },
    Normal = { fg = C.fg0, bg = opts.transparent and "NONE" or C.bg0 },
    NormalFloat = { fg = C.fg0, bg = opts.transparent and "NONE" or C.bg1 },
    FloatTitle = { fg = C.lightBlue, bold = true },
    FloatFooter = { fg = C.bg2 },
    NormalNC = { link = "Normal" },
    Pmenu = { fg = C.fg1, bg = C.bg1 },
    PmenuSel = { fg = C.bg0, bg = C.green },
    PmenuSbar = { bg = C.bg1 },
    PmenuThumb = { bg = C.grey1 },
    Question = { link = "MoreMsg" },
    QuickFixLine = { fg = C.purple },
    Search = { fg = C.bg0, bg = C.cyan },
    SpecialKey = { fg = C.fg1 },
    SpellBad = { fg = C.red, undercurl = true, sp = C.red },
    SpellCap = { fg = C.blue, undercurl = true, sp = C.blue },
    SpellLocal = { fg = C.cyan, undercurl = true, sp = C.cyan },
    SpellRare = { fg = C.purple, undercurl = true, sp = C.purple },
    StatusLine = { fg = C.grey1, bg = C.bg1 },
    StatusLineNC = { fg = C.grey0, bg = C.bg1 },
    TabLine = { fg = C.grey2, bg = C.bg3 },
    TabLineFill = { fg = C.grey1, bg = C.bg1 },
    TabLineSel = { fg = C.bg0, bg = C.green },
    Title = { fg = C.orange, bold = true },
    Visual = { bg = C.bg3 },
    VisualNOS = { bg = C.bg3 },
    WarningMsg = { fg = C.yellow, bold = true },
    Whitespace = { fg = C.bg3 },
    WildMenu = { link = "PmenuSel" },
    WinBar = { fg = C.fg1, bg = "NONE" },
    WinBarNC = { fg = C.fg1, bg = "NONE" },
    -- ┌──────────────────────┐
    -- │ Lsp highlight groups │
    -- └──────────────────────┘
    LspReferenceText = { fg = C.bg0, bg = C.darkYellow },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { fg = C.bg0, bg = C.darkYellow, underline = true },
    LspCodeLens = { fg = C.grey1 },
    LspCodeLensSeparator = { link = "LspCodeLens" },
    LspSignatureActiveParameter = { link = "Search" },
    -- ┌─────────────────────────┐
    -- │ Syntax highlight groups │
    -- └─────────────────────────┘
    Comment = { fg = C.grey1, italic = true },
    Constant = { fg = C.cyan },
    String = { fg = C.green },
    Character = { link = "String" },
    Number = { fg = C.purple },
    Boolean = { fg = C.purple },
    Float = { link = "Number" },
    Identifier = { fg = C.blue },
    Function = { fg = C.green },
    Statement = { fg = C.red, italic = true },
    Conditional = { fg = C.red },
    Repeat = { fg = C.red },
    Label = { fg = C.orange },
    Operator = { fg = C.orange },
    Keyword = { fg = C.red },
    Exception = { fg = C.red },
    PreProc = { fg = C.purple },
    Macro = { fg = C.cyan },
    Type = { fg = C.yellow },
    StorageClass = { fg = C.orange },
    Structure = { fg = C.orange },
    Special = { fg = C.yellow },
    Tag = { fg = C.orange },
    Delimiter = { fg = C.fg0 },
    SpecialComment = { fg = C.grey1, italic = true },
    Debug = { fg = C.orange },
    Underlined = { underline = true },
    Ignore = { fg = C.grey1 },
    Error = { fg = C.red },
    Todo = { fg = C.purple, italic = true },
    -- ┌─────────────┐
    -- │ Diagnostics │
    -- └─────────────┘
    DiagnosticError = { fg = C.darkRed },
    DiagnosticWarn = { fg = C.darkYellow },
    DiagnosticInfo = { fg = C.darkBlue },
    DiagnosticHint = { fg = C.darkCyan },
    DiagnosticOk = { fg = C.darkGreen },
    DiagnosticUnderlineError = { fg = C.darkRed, undercurl = true },
    DiagnosticUnderlineWarn = { fg = C.darkYellow, undercurl = true },
    DiagnosticUnderlineInfo = { fg = C.darkBlue, undercurl = true },
    DiagnosticUnderlineHint = { fg = C.darkCyan, undercurl = true },
    DiagnosticUnderlineOk = { fg = C.darkGreen, undercurl = true },
    -- ┌────────────────────────────────────────────────────────┐
    -- │ Treesitter captures (core since 0.11, not a "plugin")  │
    -- └────────────────────────────────────────────────────────┘
    ["@variable"] = { fg = C.fg0 },
    ["@variable.builtin"] = { fg = C.purple, italic = true },
    ["@variable.parameter"] = { fg = C.lightMagenta },
    ["@string.regexp"] = { fg = C.brown },
    ["@string.escape"] = { fg = C.brown, bold = true },
    ["@string.special.symbol"] = { fg = C.blue },
    ["@string.special.url"] = { fg = C.yellow, undercurl = true },
    ["@attribute"] = { link = "Constant" },
    ["@constructor"] = { fg = C.yellow },
    ["@operator"] = { link = "Operator" },
    ["@keyword.operator"] = { fg = C.orange, bold = true },
    ["@keyword.import"] = { link = "PreProc" },
    ["@punctuation.delimiter"] = { fg = C.lightMagenta },
    ["@punctuation.bracket"] = { fg = C.lightMagenta },
    ["@punctuation.special"] = { fg = C.lightMagenta },
    ["@comment.error"] = { fg = C.fg0, bg = C.darkRed, bold = true },
    ["@comment.warning"] = { fg = C.bg0, bg = C.yellow, bold = true },
    ["@comment.note"] = { fg = C.bg0, bg = C.lightBlue, bold = true },
  }
end
